---
- name: Build test home lab
  hosts: 127.0.0.1
  connection: local
  become: true
  tasks:
    # - name: Ensure hypervisor server has all required packages.
    #   ansible.builtin.dnf:
    #     name: "{{ all.hypervisor.required_packages }}"
    #     state: installed

    # - name: Get XML data of a specified network
    #   community.libvirt.virt_net:
    #     command: get_xml
    #     name: managed.test.esp.ninja

    # - name: Create the test domain networks.
    #   jm1.libvirt.net_xml:
    #     state: present
    #     xml: |
    #       <network>
    #         <name>"{{ item.name }}"</name>
    #         <uuid>''"{{ item.uuid }}"''</uuid>
    #         <forward mode='"{{ item.forward_mode }}"'>
    #           <nat>
    #             <port start='"{{ item.port_start }}"' end='"{{ item.port_end }}"'/>
    #           </nat>
    #         </forward>
    #         <bridge name='"{{ item.bridge_name }}"' stp='on' delay='0'/>
    #         <mac address='"{{ item.mac_address }}"'/>
    #         <ip address='"{{ item.ip_address }}"' netmask='"{{ item.netmask }}"'>
    #           <dhcp>
    #             <range start='"{{ item.dhcp_range_start }}"' end='"{{ item.dhcp_range_end }}"'/>
    #           </dhcp>
    #         </ip>
    #       </network>
    #   loop: "{{ test.libvirt.networks_list }}"

    - name: Create the gateway.test.esp.ninja domain.
      jm1.libvirt.net_xml:
        state: present
        xml: |
          <network>
            <name>gateway.test.esp.ninja</name>
            <uuid>f57fefb5-b284-4b64-a6d6-dfa1dfe70280</uuid>
            <forward mode='nat'>
              <nat>
                <port start='1024' end='65535'/>
              </nat>
            </forward>
            <bridge name='virbr1' stp='on' delay='0'/>
            <mac address='52:54:00:50:00:01'/>
            <domain name='gateway.test.esp.ninja' localOnly='yes'/>
            <ip address='192.168.10.1' netmask='255.255.255.0'>
              <dhcp>
                <range start='192.168.10.2' end='192.168.10.254'/>
              </dhcp>
            </ip>
          </network>

    - name: Create the management.test.esp.ninja domain.
      jm1.libvirt.net_xml:
        state: present
        xml: |
          <network>
            <name>management.test.esp.ninja</name>
            <uuid>f57fefb5-b284-4b64-a6d6-efa1dfe70290</uuid>
            <forward mode='nat'>
              <nat>
                <port start='1024' end='65535'/>
              </nat>
            </forward>
            <bridge name='virbr2' stp='on' delay='0'/>
            <mac address='52:54:00:50:00:02'/>
            <domain name='management.test.esp.ninja' localOnly='yes'/>
            <ip address='192.168.11.1' netmask='255.255.255.0'>
              <dhcp>
                <range start='192.168.11.2' end='192.168.11.254'/>
              </dhcp>
            </ip>
          </network>

    - name: Create the managed.test.esp.ninja domain.
      jm1.libvirt.net_xml:
        state: present
        xml: |
          <network>
            <name>managed.test.esp.ninja</name>
            <uuid>f57fefb5-b284-4b64-a6d6-ffa1dfe70203</uuid>
            <forward mode='nat'>
              <nat>
                <port start='1024' end='65535'/>
              </nat>
            </forward>
            <bridge name='virbr3' stp='on' delay='0'/>
            <mac address='52:54:00:50:00:03'/>
            <domain name='managed.test.esp.ninja' localOnly='yes'/>
            <ip address='192.168.13.1' netmask='255.255.255.0'>
              <dhcp>
                <range start='192.168.13.2' end='192.168.13.254'/>
              </dhcp>
            </ip>
          </network>

# Networks added, but not started. Needed to manually start the networks.
    - name: Start the networks.
      community.libvirt.virt_net:
        autostart: true
        command: start
        name: "{{ item.name }}"
      loop: "{{ test.libvirt.networks_list }}"

    - name: Create storage pools.
      jm1.libvirt.pool:
        name: "{{ item.name }}"
        hardware: [{'type': '"{{ item.hardware.type }}"', 'target': '"{{ item.hardware.target }}"'}]
      loop: "{{ test.libvirt.storage_pools_list }}"

    - name: Create a new volume disks
      jm1.libvirt.volume:
        pool: "{{ item.pool }}"
        name: "{{ item.name }}"
        capacity: "{{ item.capacity }}"
      loop: "{{ test.libvirt.storage_volumes_list }}"

    - name: Create VMs
      jm1.libvirt.domain:
        name: "{{ item.name }}"
        hardware:
          - boot: "{{ item.boot }}"
          # - cdrom: "{{ item.cdrom }}"
          - cpu: "{{ item.cpu }}"
          - disk: "{{ item.disk }}"
          - extra_args: "{{ item.extra_args }}"
          - initrd_inject: "{{ item.initrd_inject }}"
          - location: "{{ item.location }}"
          - vcpus: "{{ item.vcpus }}"
          - memory: "{{ item.memory }}"
          - network: "{{ item.network }}"
          - virt_type: "{{ item.virt_type }}"
          - graphics: "{{ item.graphics }}"
          - os_variant: "{{ item.os_variant }}"
      loop: "{{ test.libvirt.domains_list }}"

    - name: Stop VMs
      community.libvirt.virt:
        name: "{{ item.name }}"
        state: shutdown
      loop: "{{ test.libvirt.domains_list }}"

    - name: Start VMs
      community.libvirt.virt:
        name: "{{ item.name }}"
        state: running
      loop: "{{ test.libvirt.domains_list }}"
