---
- name: Build test home lab
  hosts: esp_machine
  become: true
  gather_facts: false
  tasks:
    - name: Ensure hypervisor server has all required packages.
      ansible.builtin.dnf:
        name: "{{ all.hypervisor.required_packages }}"
        state: installed

    - name: Create the test domain networks.
      jm1.libvirt.net_xml:
        state: present
        xml: |-
          <network>
            <name>{{ item.name }}</name>
            <uuid>{{ item.uuid | to_uuid }}</uuid>
            <forward mode="{{ item.forward_mode }}">
              <nat>
                <port start="{{ item.port_start }}" end="{{ item.port_end }}"/>
              </nat>
            </forward>
            <bridge name="{{ item.bridge_name }}" stp="on" delay="0"/>
            <mac address="{{ item.mac_address }}"/>
            <ip address="{{ item.ip_address }}" netmask="{{ item.netmask }}">
              <dhcp>
                <range start="{{ item.dhcp_range_start }}" end="{{ item.dhcp_range_end }}"/>
              </dhcp>
            </ip>
          </network>
      loop: "{{ test.libvirt.networks_list }}"

# Networks added, but not started. Needed to manually start the networks.
    - name: Start the networks.
      community.libvirt.virt_net:
        autostart: true
        command: start
        name: "{{ item.name }}"
      loop: "{{ test.libvirt.networks_list }}"

    - name: Create storage pools.
      jm1.libvirt.pool:
        name: "{{ item.name }}"
        hardware: [{'type': '"{{ item.hardware.type }}"', 'target': '"{{ item.hardware.target }}"'}]
      loop: "{{ test.libvirt.storage_pools_list }}"

    - name: Create a new volume disks
      jm1.libvirt.volume:
        pool: "{{ item.pool }}"
        name: "{{ item.name }}"
        capacity: "{{ item.capacity }}"
      loop: "{{ test.libvirt.storage_volumes_list }}"

    - name: Download dvd iso
      ansible.builtin.copy:
        src: /var/lib/libvirt/images/rhel-8.10-x86_64-dvd.iso
        dest: /var/lib/libvirt/images/rhel-8.10-x86_64-dvd.iso
        owner: qemu
        group: qemu
        mode: '0644'

    - name: Download kickstart file
      ansible.builtin.copy:
        src: ./files/satellite_kickstart.txt
        dest: /var/lib/libvirt/images
        owner: root
        group: root
        mode: '0644'

    - name: Create VMs
      jm1.libvirt.domain:
        name: "{{ item.name }}"
        hardware:
          - boot: "{{ item.boot }}"
          # - cdrom: "{{ item.cdrom }}"
          - cpu: "{{ item.cpu }}"
          - disk: "{{ item.disk }}"
          - extra_args: "{{ item.extra_args }}"
          - initrd_inject: "{{ item.initrd_inject }}"
          - location: "{{ item.location }}"
          - vcpus: "{{ item.vcpus }}"
          - memory: "{{ item.memory }}"
          - network: "{{ item.network }}"
          - virt_type: "{{ item.virt_type }}"
          - graphics: "{{ item.graphics }}"
          - os_variant: "{{ item.os_variant }}"
      loop: "{{ test.libvirt.domains_list }}"

    - name: Stop VMs
      community.libvirt.virt:
        name: "{{ item.name }}"
        state: shutdown
      loop: "{{ test.libvirt.domains_list }}"

    - name: Start VMs
      community.libvirt.virt:
        name: "{{ item.name }}"
        state: running
      loop: "{{ test.libvirt.domains_list }}"
